{% set name = "speedcopy" %}
{% set version = "2.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/speedcopy-{{ version }}.tar.gz
  sha256: 1b2d779fadebd53a59384f7d286c40b2ef382e0d000fa53011699fcd3190d33f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core
  run:
    - python >=3.6

test:
  imports:
    - speedcopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/antirotor/speedcopy
  summary: Replacement or alternative for python copyfile() utilizing server side copy on network shares for faster copying.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
