{% set name = "speedcopy" %}
{% set version = "2.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/speedcopy-{{ version }}.tar.gz
  sha256: eff007a97e49ec1934df4fa8074f4bd1cf4a3b14c5499d914988785cff0c199a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - speedcopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/antirotor/speedcopy
  summary: Replacement or alternative for python copyfile() utilizing server side copy on network shares for faster copying.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
